// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: core/proto/base/base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter_Cond int32

const (
	Filter_None Filter_Cond = 0
	// a = ?
	Filter_Eq Filter_Cond = 1
	// a <> ?
	Filter_Neq Filter_Cond = 2
	// a > ?
	Filter_Gt Filter_Cond = 3
	// a >= ?
	Filter_Gte Filter_Cond = 4
	// a < ?
	Filter_Lt Filter_Cond = 5
	// a <= ?
	Filter_Lte Filter_Cond = 6
	// a Like ?
	Filter_Like Filter_Cond = 7
	// a IN (?,?,?)
	Filter_In Filter_Cond = 8
	// a NOT IN (?, ?, ?)
	Filter_NotIn Filter_Cond = 9
	// a IS NULL []
	Filter_IsNull Filter_Cond = 10
	// a IS NOT NULL []
	Filter_NotNull Filter_Cond = 11
	// a BETWEEN 1 AND 2
	Filter_Between Filter_Cond = 12
)

// Enum value maps for Filter_Cond.
var (
	Filter_Cond_name = map[int32]string{
		0:  "None",
		1:  "Eq",
		2:  "Neq",
		3:  "Gt",
		4:  "Gte",
		5:  "Lt",
		6:  "Lte",
		7:  "Like",
		8:  "In",
		9:  "NotIn",
		10: "IsNull",
		11: "NotNull",
		12: "Between",
	}
	Filter_Cond_value = map[string]int32{
		"None":    0,
		"Eq":      1,
		"Neq":     2,
		"Gt":      3,
		"Gte":     4,
		"Lt":      5,
		"Lte":     6,
		"Like":    7,
		"In":      8,
		"NotIn":   9,
		"IsNull":  10,
		"NotNull": 11,
		"Between": 12,
	}
)

func (x Filter_Cond) Enum() *Filter_Cond {
	p := new(Filter_Cond)
	*p = x
	return p
}

func (x Filter_Cond) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filter_Cond) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_base_base_proto_enumTypes[0].Descriptor()
}

func (Filter_Cond) Type() protoreflect.EnumType {
	return &file_core_proto_base_base_proto_enumTypes[0]
}

func (x Filter_Cond) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filter_Cond.Descriptor instead.
func (Filter_Cond) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_base_base_proto_rawDescGZIP(), []int{0, 0}
}

type Filter_OrderByDerection int32

const (
	Filter_Asc  Filter_OrderByDerection = 0
	Filter_Desc Filter_OrderByDerection = 1
)

// Enum value maps for Filter_OrderByDerection.
var (
	Filter_OrderByDerection_name = map[int32]string{
		0: "Asc",
		1: "Desc",
	}
	Filter_OrderByDerection_value = map[string]int32{
		"Asc":  0,
		"Desc": 1,
	}
)

func (x Filter_OrderByDerection) Enum() *Filter_OrderByDerection {
	p := new(Filter_OrderByDerection)
	*p = x
	return p
}

func (x Filter_OrderByDerection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filter_OrderByDerection) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_base_base_proto_enumTypes[1].Descriptor()
}

func (Filter_OrderByDerection) Type() protoreflect.EnumType {
	return &file_core_proto_base_base_proto_enumTypes[1]
}

func (x Filter_OrderByDerection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filter_OrderByDerection.Descriptor instead.
func (Filter_OrderByDerection) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_base_base_proto_rawDescGZIP(), []int{0, 1}
}

// 查询条件
type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Filter:
	//	*Filter_And_
	//	*Filter_Or_
	//	*Filter_OrderBy_
	Filter isFilter_Filter `protobuf_oneof:"filter"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_base_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_base_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_core_proto_base_base_proto_rawDescGZIP(), []int{0}
}

func (m *Filter) GetFilter() isFilter_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (x *Filter) GetAnd() *Filter_And {
	if x, ok := x.GetFilter().(*Filter_And_); ok {
		return x.And
	}
	return nil
}

func (x *Filter) GetOr() *Filter_Or {
	if x, ok := x.GetFilter().(*Filter_Or_); ok {
		return x.Or
	}
	return nil
}

func (x *Filter) GetOrderBy() *Filter_OrderBy {
	if x, ok := x.GetFilter().(*Filter_OrderBy_); ok {
		return x.OrderBy
	}
	return nil
}

type isFilter_Filter interface {
	isFilter_Filter()
}

type Filter_And_ struct {
	And *Filter_And `protobuf:"bytes,1,opt,name=and,proto3,oneof"`
}

type Filter_Or_ struct {
	Or *Filter_Or `protobuf:"bytes,2,opt,name=or,proto3,oneof"`
}

type Filter_OrderBy_ struct {
	OrderBy *Filter_OrderBy `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3,oneof"`
}

func (*Filter_And_) isFilter_Filter() {}

func (*Filter_Or_) isFilter_Filter() {}

func (*Filter_OrderBy_) isFilter_Filter() {}

type Debug struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogLevel string `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	ShowSql  bool   `protobuf:"varint,2,opt,name=show_sql,json=showSql,proto3" json:"show_sql,omitempty"`
}

func (x *Debug) Reset() {
	*x = Debug{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_base_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Debug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debug) ProtoMessage() {}

func (x *Debug) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_base_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debug.ProtoReflect.Descriptor instead.
func (*Debug) Descriptor() ([]byte, []int) {
	return file_core_proto_base_base_proto_rawDescGZIP(), []int{1}
}

func (x *Debug) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Debug) GetShowSql() bool {
	if x != nil {
		return x.ShowSql
	}
	return false
}

// and 条件
type Filter_And struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 条件 enum Cond
	Cond string `protobuf:"bytes,1,opt,name=cond,proto3" json:"cond,omitempty"`
	// 字段
	Column string `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	// 判断参数
	Args []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *Filter_And) Reset() {
	*x = Filter_And{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_base_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_And) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_And) ProtoMessage() {}

func (x *Filter_And) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_base_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_And.ProtoReflect.Descriptor instead.
func (*Filter_And) Descriptor() ([]byte, []int) {
	return file_core_proto_base_base_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Filter_And) GetCond() string {
	if x != nil {
		return x.Cond
	}
	return ""
}

func (x *Filter_And) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Filter_And) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// or 条件
type Filter_Or struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 条件
	Cond string `protobuf:"bytes,1,opt,name=cond,proto3" json:"cond,omitempty"`
	// 字段
	Column string `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	// 参数
	Args []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *Filter_Or) Reset() {
	*x = Filter_Or{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_base_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_Or) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_Or) ProtoMessage() {}

func (x *Filter_Or) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_base_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_Or.ProtoReflect.Descriptor instead.
func (*Filter_Or) Descriptor() ([]byte, []int) {
	return file_core_proto_base_base_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Filter_Or) GetCond() string {
	if x != nil {
		return x.Cond
	}
	return ""
}

func (x *Filter_Or) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Filter_Or) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// order by
type Filter_OrderBy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 条件
	OrderByDirection Filter_OrderByDerection `protobuf:"varint,1,opt,name=order_by_direction,json=orderByDirection,proto3,enum=base.Filter_OrderByDerection" json:"order_by_direction,omitempty"`
	//字段
	Column string `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *Filter_OrderBy) Reset() {
	*x = Filter_OrderBy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_base_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_OrderBy) ProtoMessage() {}

func (x *Filter_OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_base_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_OrderBy.ProtoReflect.Descriptor instead.
func (*Filter_OrderBy) Descriptor() ([]byte, []int) {
	return file_core_proto_base_base_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Filter_OrderBy) GetOrderByDirection() Filter_OrderByDerection {
	if x != nil {
		return x.OrderByDirection
	}
	return Filter_Asc
}

func (x *Filter_OrderBy) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

var File_core_proto_base_base_proto protoreflect.FileDescriptor

var file_core_proto_base_base_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x22, 0xbb, 0x04, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x24, 0x0a,
	0x03, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x03,
	0x61, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x02, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4f, 0x72,
	0x48, 0x00, 0x52, 0x02, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x48, 0x00,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x1a, 0x45, 0x0a, 0x03, 0x41, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x1a, 0x44, 0x0a, 0x02, 0x4f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x1a, 0x6e, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x79, 0x12, 0x4b, 0x0a, 0x12, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x5f, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x79, 0x44, 0x65, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x42, 0x79, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x86, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x64, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x45, 0x71, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x65, 0x71, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x74,
	0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x74, 0x65, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x4c,
	0x74, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x74, 0x65, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04,
	0x4c, 0x69, 0x6b, 0x65, 0x10, 0x07, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x6e, 0x10, 0x08, 0x12, 0x09,
	0x0a, 0x05, 0x4e, 0x6f, 0x74, 0x49, 0x6e, 0x10, 0x09, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x73, 0x4e,
	0x75, 0x6c, 0x6c, 0x10, 0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x4e, 0x75, 0x6c, 0x6c,
	0x10, 0x0b, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x10, 0x0c, 0x22,
	0x25, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x44, 0x65, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x73, 0x63, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x44, 0x65, 0x73, 0x63, 0x10, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x22, 0x3f, 0x0a, 0x05, 0x44, 0x65, 0x62, 0x75, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x67,
	0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f,
	0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x73,
	0x71, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x68, 0x6f, 0x77, 0x53, 0x71,
	0x6c, 0x42, 0x1c, 0x5a, 0x1a, 0x78, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x63, 0x6e, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_proto_base_base_proto_rawDescOnce sync.Once
	file_core_proto_base_base_proto_rawDescData = file_core_proto_base_base_proto_rawDesc
)

func file_core_proto_base_base_proto_rawDescGZIP() []byte {
	file_core_proto_base_base_proto_rawDescOnce.Do(func() {
		file_core_proto_base_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_proto_base_base_proto_rawDescData)
	})
	return file_core_proto_base_base_proto_rawDescData
}

var file_core_proto_base_base_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_core_proto_base_base_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_core_proto_base_base_proto_goTypes = []interface{}{
	(Filter_Cond)(0),             // 0: base.Filter.Cond
	(Filter_OrderByDerection)(0), // 1: base.Filter.OrderByDerection
	(*Filter)(nil),               // 2: base.Filter
	(*Debug)(nil),                // 3: base.Debug
	(*Filter_And)(nil),           // 4: base.Filter.And
	(*Filter_Or)(nil),            // 5: base.Filter.Or
	(*Filter_OrderBy)(nil),       // 6: base.Filter.OrderBy
}
var file_core_proto_base_base_proto_depIdxs = []int32{
	4, // 0: base.Filter.and:type_name -> base.Filter.And
	5, // 1: base.Filter.or:type_name -> base.Filter.Or
	6, // 2: base.Filter.order_by:type_name -> base.Filter.OrderBy
	1, // 3: base.Filter.OrderBy.order_by_direction:type_name -> base.Filter.OrderByDerection
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_proto_base_base_proto_init() }
func file_core_proto_base_base_proto_init() {
	if File_core_proto_base_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_proto_base_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_base_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Debug); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_base_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_And); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_base_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_Or); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_base_base_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_OrderBy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_core_proto_base_base_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Filter_And_)(nil),
		(*Filter_Or_)(nil),
		(*Filter_OrderBy_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_proto_base_base_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_base_base_proto_goTypes,
		DependencyIndexes: file_core_proto_base_base_proto_depIdxs,
		EnumInfos:         file_core_proto_base_base_proto_enumTypes,
		MessageInfos:      file_core_proto_base_base_proto_msgTypes,
	}.Build()
	File_core_proto_base_base_proto = out.File
	file_core_proto_base_base_proto_rawDesc = nil
	file_core_proto_base_base_proto_goTypes = nil
	file_core_proto_base_base_proto_depIdxs = nil
}
