// Code generated by protoc-gen-stack. DO NOT EDIT.
// source: proto/cman/cman.proto

package cman

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "git.xswitch.cn/xswitch/xctrl/xctrl/api"
	client "git.xswitch.cn/xswitch/xctrl/xctrl/client"
	server "git.xswitch.cn/xswitch/xctrl/xctrl/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CMan service

func NewCManEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CMan service

type CManService interface {
	// 获取会议列表
	GetConferenceList(ctx context.Context, in *GetConferenceListRequest, opts ...client.CallOption) (*GetConferenceListResponse, error)
	// 获取会议信息
	ConferenceInfo(ctx context.Context, in *ConferenceInfoRequest, opts ...client.CallOption) (*ConferenceInfoResponse, error)
}

type cManService struct {
	c    client.Client
	name string
}

func NewCManService(name string, c client.Client) CManService {
	return &cManService{
		c:    c,
		name: name,
	}
}

func (c *cManService) GetConferenceList(ctx context.Context, in *GetConferenceListRequest, opts ...client.CallOption) (*GetConferenceListResponse, error) {
	req := c.c.NewRequest(c.name, "getConferenceList", in)
	out := new(GetConferenceListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cManService) ConferenceInfo(ctx context.Context, in *ConferenceInfoRequest, opts ...client.CallOption) (*ConferenceInfoResponse, error) {
	req := c.c.NewRequest(c.name, "conferenceInfo", in)
	out := new(ConferenceInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CMan service

type CManHandler interface {
	// 获取会议列表
	GetConferenceList(context.Context, *GetConferenceListRequest, *GetConferenceListResponse) error
	// 获取会议信息
	ConferenceInfo(context.Context, *ConferenceInfoRequest, *ConferenceInfoResponse) error
}

func RegisterCManHandler(s server.Server, hdlr CManHandler, opts ...server.HandlerOption) error {
	type cMan interface {
		GetConferenceList(ctx context.Context, in *GetConferenceListRequest, out *GetConferenceListResponse) error
		ConferenceInfo(ctx context.Context, in *ConferenceInfoRequest, out *ConferenceInfoResponse) error
	}
	type CMan struct {
		cMan
	}
	h := &cManHandler{hdlr}
	return s.Handle(s.NewHandler(&CMan{h}, opts...))
}

type cManHandler struct {
	CManHandler
}

func (h *cManHandler) GetConferenceList(ctx context.Context, in *GetConferenceListRequest, out *GetConferenceListResponse) error {
	return h.CManHandler.GetConferenceList(ctx, in, out)
}

func (h *cManHandler) ConferenceInfo(ctx context.Context, in *ConferenceInfoRequest, out *ConferenceInfoResponse) error {
	return h.CManHandler.ConferenceInfo(ctx, in, out)
}
